version: '3.2'

services:
  app:
    build: .
    container_name: app
    volumes:
      - .:/var/www
    depends_on:
      - db
    links:
      - db
    ports:
      - 8000:80
    networks:
      - default
  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123
    networks:
      - default
    volumes:
      - ./db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    restart: always
    links:
      - db
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - default
networks:
  default:
    driver: bridge